version: '3.5'
services:
  mysql:
    image: mysql
    container_name: mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: docker 
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log/mysql:/var/log/mysql
    hostname: mysql
    ports:
      - "3306:3306"
  api:
    depends_on:
      - mysql
    container_name: api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    tty: true
    volumes:
      - ./api:/go/src/github.com/Kazuki-Tohyama/go-nuxt-blog/api
    ports:
      - "8080:8080" 
  nuxt:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    tty: true
    command: yarn run dev
    volumes:
      - ./frontend:/go/src/github.com/Kazuki-Tohyama/go-nuxt-blog/frontend
    ports:
      - "3000:3000"
