version: '3.5'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    tty: true
    volumes:
      - ./api:/go/src/github.com/Kazuki-Tohyama/go-nuxt-blog/api

